name: Build Android APK

on:
  push:
    branches: [ "main" ]

env:
  APP_ID: com.boss.coolapp      # <— change to your package id
  APP_NAME: MyCoolApp           # <— change app name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3️⃣ Setup Java 17
      - name: Setup Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      # 4️⃣ Setup Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # 5️⃣ Install Cordova
      - name: Install Cordova
        run: npm install -g cordova

      # 6️⃣ Build Cordova app
      - name: Build APK
        run: bash tools/build.sh

      # 8️⃣ Upload all APKs found
      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MyCoolApp-APK
          path: ${{ github.workspace }}/app/platforms/android/app/build/outputs/apk/**/*.apk
