name: Build Android APK

on:
  push:
    branches: [ "main" ]

env:
  APP_ID: com.boss.coolapp      # <— change to your package id when you want
  APP_NAME: MyCoolApp           # <— change app name if you like

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Cordova
        run: npm install -g cordova

      - name: Build with Cordova
        run: bash tools/build.sh


      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MyCoolApp-APK
          path: app/platforms/android/app/build/outputs/apk/debug/app-debug.apk

